### ISSUE TITLE
Request for docs on built-in operators

### ISSUE THREAD

**Issue by eatonphil** [briansteffens/bshift#12]
What operators are supported? What data do they operate on? In particular, what can I use == on? Just (all) primitives? Will == on strings check that they are the same string in memory?

**Comment by briansteffens** [comment]
The current implementation isn't complete. I haven't thought much about how operators really should work, other than probably wanting to support operator overloading to some degree. Right now ==, !=, >, <, >=, <= just generate the cmp instruction which compares integers. They work the way you'd expect for u64 and u8. For pointers they'll compare the pointer address. The only strings in place currently are C-style strings (u8*) so those will not compare string value, they'll compare the address of the string.

**Comment by eatonphil** [comment]
Great improvement on the docs. Closing.
