### ISSUE TITLE
Request for benchmarks

### ISSUE THREAD

**Issue by eatonphil** [briansteffens/bshift#17]
It would be great to have some benchmarks to run in bshift and comparable languages. Comparable could be in terms of practical functionality (so maybe C, DLang, C++, Java, CL) or in terms of desired functionality (so maybe Ruby, Python, Javascript, Scheme). Optimizations are fun and there should be some low-hanging fruit in these early stages. But it's impossible to tell what's changed (/doesn't feel as good) without having benchmarks to point to. We could probably hook travis up to store data and treat introduced latency as CI failure.

**Comment by briansteffens** [comment]
Yeah there is tons of low-hanging fruit. This would be cool.

**Comment by eatonphil** [comment]
Closing this out for you.
